name: Build

on:
  push:
  pull_request:
    types:
      - opened
      - edited
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11' # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64

    - name: Build
      run: ./build-and-test-all-mysql-binlog.sh

    - name: Save test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: ./end-to-end-tests/build/reports

    - name: print messages
      run: ./.github/workflows/dump-messages.sh
      if: ${{ failure() }}

    - name: get container logs
      run: ./.github/workflows/print-container-logs.sh
      if: ${{ always() }}

    - name: Save container logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: container-logs
        path: ~/container-logs
